Add turbo-tests logo
serpapi/turbo_tests pull request #32
Opened 2023-04-24 06:06 UTC by dimitryzub

This PR adds a logo for `turbo_tests`, and centers tests workflow badge under the repo logo.

Logo `width="500"` could be adjusted. Currently (this PR), it looks something like this:

![image](https://user-images.githubusercontent.com/78694043/233912297-3f0b7bad-ed20-435d-a9e9-75d484e50e95.png)

2023-04-26 12:17 UTC, ilyazub requested changes
Thank you, @dimitryzub :100: I like this logo!

Please fix the link that build badge points to.

2023-04-27 08:04 UTC, dimitryzub commented on README.md
> +  <a href="">![Tests](https://github.com/serpapi/turbo_tests/workflows/Tests/badge.svg)</a>
I though plain markdown can't be wrapped by HTML (`<div>` in this case) and used `<a>` tag 🙂

2023-05-01 05:06 UTC, dimitryzub commented
@ilyazub What do you think about PNG instead of SVG? Example below:

<h1 align="center">
  TurboTests
</h1>

<div align="center">
   <img src="https://user-images.githubusercontent.com/78694043/235409351-6acb98fb-fb9a-4507-8080-360d0c629865.png" width="500" alt="Turbo-Tests-Logo">
  
</div>

<div align="center">

  ![Tests](https://github.com/serpapi/turbo_tests/workflows/Tests/badge.svg)

</div>

2023-05-01 08:50 UTC, ilyazub approved these changes
lgtm :100:

2023-05-01 08:50 UTC, merged