Cleanup temp directory on completion
serpapi/turbo_tests pull request #47
Opened 2023-12-17 02:56 UTC by Bo98

The `tmp` directory is currently fixed to the working directory and is never cleaned up. We can make use of `Dir.mktmpdir` to have a temporary directory that will clean up itself.

2024-01-17 17:27 UTC, ilyazub requested changes
@Bo98 thanks for your work and my apologies for not reviewing your PRs sooner.

Let's make `wait_threads` available outside of the `setup_tmp_dir` block or explicitly clean up the folder instead.

TIL `Dir.mktmpdir`. Thank you for that!

2024-01-17 17:27 UTC, ilyazub commented on lib/turbo_tests/runner.rb
>        @reporter.failed_examples.empty? && wait_threads.map(&:value).all?(&:success?)
`wait_threads` are not defined now.

```
$ bundle exec turbo_tests
Using recorded test runtime
3 processes for 3 specs, ~ 1 specs per process

Randomized with seed 35942

.bundler: failed to load command: turbo_tests (~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bin/turbo_tests)
~/Workspace/turbo_tests/lib/turbo_tests/runner.rb:110:in `run': undefined local variable or method `wait_threads' for #<TurboTests::Runner:0x00000000015fd588> (NameError)
	from ~/Workspace/turbo_tests/lib/turbo_tests/runner.rb:43:in `run'
	from ~/Workspace/turbo_tests/lib/turbo_tests/cli.rb:101:in `run'
	from ~/Workspace/turbo_tests/bin/turbo_tests:11:in `<top (required)>'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bin/turbo_tests:23:in `load'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bin/turbo_tests:23:in `<top (required)>'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:58:in `load'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:23:in `run'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/cli.rb:492:in `exec'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/cli.rb:34:in `dispatch'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/cli.rb:28:in `start'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/exe/bundle:37:in `block in <top (required)>'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/exe/bundle:29:in `<top (required)>'
	from ~/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
	from ~/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
..bundler: failed to load command: turbo_tests (~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bin/turbo_tests)
~/Workspace/turbo_tests/lib/turbo_tests/runner.rb:110:in `run': undefined local variable or method `wait_threads' for #<TurboTests::Runner:0x00000000023c1548> (NameError)
	from ~/Workspace/turbo_tests/lib/turbo_tests/runner.rb:43:in `run'
	from ~/Workspace/turbo_tests/lib/turbo_tests/cli.rb:101:in `run'
	from ~/Workspace/turbo_tests/bin/turbo_tests:11:in `<top (required)>'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bin/turbo_tests:23:in `load'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bin/turbo_tests:23:in `<top (required)>'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:58:in `load'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:23:in `run'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/cli.rb:492:in `exec'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/cli.rb:34:in `dispatch'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/cli.rb:28:in `start'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/exe/bundle:37:in `block in <top (required)>'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/exe/bundle:29:in `<top (required)>'
	from ~/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
	from ~/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
F..

Failures:

  1) TurboTests::CLI pending exceptions reports
     Failure/Error: expect($?.exitstatus).to eql(0)
     
       expected: 0
            got: 1
     
       (compared using eql?)
     # ./spec/cli_spec.rb:44:in `block (3 levels) in <top (required)>'

Finished in 3.33 seconds (files took 3.12 seconds to load)
6 examples, 1 failure, 1 error occurred outside of examples

Failed examples:

rspec ./spec/cli_spec.rb:43 # TurboTests::CLI pending exceptions reports


Randomized with seed 35942
```

2024-01-17 17:27 UTC, ilyazub commented on lib/turbo_tests/runner.rb
> +      Dir.mktmpdir("turbo_tests-pipes", &block)
Let's follow ParallelTests's convention of using `./tmp` folder.

```suggestion
      Dir.mktmpdir("turbo_tests-pipes", "tmp", &block)
```

```ruby
Dir.mktmpdir("turbo_tests-pipes", "tmp") { |tmp| puts tmp }
# tmp/turbo_tests-pipes20240117-61561-5k7jqw
# nil
```

2025-02-04 14:19 UTC, pboling commented
@ilyazub `tmp` dir logic is now vestigial.  I think this can be closed.

2025-03-07 14:32 UTC, ilyazub commented
@pboling Right, thanks for double-checking it! I merged #67.

@Bo98 Thank you for your work on that PR! I'm sorry I missed the fact `tmp` directory wasn't used anymore.

2025-03-07 14:32 UTC, closed without merging